[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

; Stage 1 - Network Analysis Portal (port 8001)
[program:stage1]
command=python3 /opt/ctf/stages/stage1/server.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

; Stage 2 - Signal Intelligence (port 8002)
[program:stage2]
command=python3 /opt/ctf/stages/stage2/server.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

; Stage 3 - Internal Diagnostic Console (port 8003)
[program:stage3]
command=python3 /opt/ctf/stages/stage3/server.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

; Stage 4 - Live exploit target (port 9004, socat --> binary)
[program:stage4_service]
command=socat TCP-LISTEN:9004,reuseaddr,fork EXEC:/opt/ctf/stages/stage4/vuln,stderr
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0